   # This is a basic workflow to help you get started with Actions

name: Start Cron Job

       # Controls when the workflow will run
on:
  # Triggers the workflow every 7 minutes
  schedule:
    - cron: "0 5 * * 6,0,1,2,3"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Start The App.
